//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_LOGIN_PAGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int E_ID { get; set; }
        public string E_Name { get; set; }
        public int? E_Salary { get; set; }
        public string E_Company { get; set; }
        public string E_Dept { get; set; }
        public string E_Email_Id { get; set; }
        public string UserName { get; set; }
        public string password { get; set; }
    }
}
